### ISSUE TITLE
Latest update crash

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#90]
After latest updates bot crashes on start. I did clean build.
```
arbitrader_1  | 2019-05-05 20:42:57.652  WARN 1 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tradingService': Invocation of init method failed; nested exception is org.knowm.xchange.exceptions.NonceException: EAPI:Invalid nonce
arbitrader_1  | 2019-05-05 20:42:57.821 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
arbitrader_1  |
arbitrader_1  | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tradingService': Invocation of init method failed; nested exception is org.knowm.xchange.exceptions.NonceException: EAPI:Invalid nonce
arbitrader_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
arbitrader_1  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
arbitrader_1  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
arbitrader_1  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
arbitrader_1  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
arbitrader_1  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
arbitrader_1  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
arbitrader_1  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
arbitrader_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
arbitrader_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
arbitrader_1  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
arbitrader_1  | 	at com.r307.arbitrader.Arbitrader.main(Arbitrader.java:11)
arbitrader_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
arbitrader_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
arbitrader_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
arbitrader_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
arbitrader_1  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
arbitrader_1  | 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
arbitrader_1  | Caused by: org.knowm.xchange.exceptions.NonceException: EAPI:Invalid nonce
arbitrader_1  | 	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:78)
arbitrader_1  | 	at org.knowm.xchange.kraken.service.KrakenAccountServiceRaw.getKrakenBalance(KrakenAccountServiceRaw.java:62)
arbitrader_1  | 	at org.knowm.xchange.kraken.service.KrakenAccountService.getAccountInfo(KrakenAccountService.java:43)
arbitrader_1  | 	at com.r307.arbitrader.service.TradingService.getAccountBalance(TradingService.java:1033)
arbitrader_1  | 	at com.r307.arbitrader.service.TradingService.getAccountBalance(TradingService.java:1048)
arbitrader_1  | 	at com.r307.arbitrader.service.TradingService.getAccountBalance(TradingService.java:1054)
arbitrader_1  | 	at com.r307.arbitrader.service.TradingService.lambda$connectExchanges$3(TradingService.java:146)
arbitrader_1  | 	at java.util.ArrayList.forEach(ArrayList.java:1257)
arbitrader_1  | 	at com.r307.arbitrader.service.TradingService.connectExchanges(TradingService.java:129)
arbitrader_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
arbitrader_1  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
arbitrader_1  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
arbitrader_1  | 	at java.lang.reflect.Method.invoke(Method.java:498)
arbitrader_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
arbitrader_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
arbitrader_1  | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
arbitrader_1  | 	... 25 common frames omitted
arbitrader_1  |
arbitrader_arbitrader_1 exited with code 1
```

NonceException: EAPI:Invalid nonce ?

**Comment by scionaltera** [comment]
Do you have more than one copy of Arbitrader running at the same time with the same API key?

**Comment by sanitariu** [comment]
No i do not but for some reason kraken needed new key. I did it and now everything is running....
